package cloud.autotests.tests;

import cloud.autotests.helpers.DriverUtils;
import io.qameta.allure.Description;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static com.codeborne.selenide.Selenide.open;
import static com.codeborne.selenide.Selenide.title;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class GeneratedTests extends TestBase {
    @Test
    @Description("Soon to be implemented by you (or QA.GURU engineers)")
    @DisplayName("Удеми")
    void generatedTest() {
        step("Открыть https://www.udemy.com/join/login-popup/?locale=ru_RU&response_type=html&next=https%3A%2F%2Fwww.udemy.com%2Fcourse%2Fqaengineer%2F", () -> {
            step("// todo: just add selenium action");
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://www.udemy.com/join/login-popup/?locale=ru_RU&response_type=html&next=https%3A%2F%2Fwww.udemy.com%2Fcourse%2Fqaengineer%2F'", () ->
            open("https://www.udemy.com/join/login-popup/?locale=ru_RU&response_type=html&next=https%3A%2F%2Fwww.udemy.com%2Fcourse%2Fqaengineer%2F"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = DriverUtils.getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}